<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CapFinLoan.Wallet.Application\CapFinLoan.Wallet.Application.csproj" />
    <ProjectReference Include="..\CapFinLoan.Wallet.Domain\CapFinLoan.Wallet.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
